
class Routes(object):

  TROLLEYS = [
    ("10", "10 - Overbrook to Center City"),
    ("11", "11 - Darby Trans. Ctr. to Center City"),
    ("13", "13 - Yeadon and Darby Trans. Ctr. to Center City"),
    ("15", "15 - Port Richmond to Haddington"),
    ("34", "34 - Angora to Center City"),
    ("36", "36 - Eastwick to Center City"),
    ("101", "101 - 69th Street Trans. Ctr. to Media"),
    ("102", "102 - 69th Street Trans. Ctr. to Sharon Hill"),
  ]

  BUSES = [
    ("1", "1 - Phila. Park & Parx Casino to 54th & City Ave."),
    ("2", "2 - Nicetown to South Philadelphia"),
    ("3", "3 - Strawberry Mansion to Frankford Trans. Ctr."),
    ("5", "5 - Pennls Landing to Frankford Trans. Ctr."),
    ("6", "6 - West Oak Lane to Olney Trans. Ctr."),
    ("7", "7 - Strawberry Mansion to Pier 70"),
    ("8", "8 - Olney Trans. Ctr. to Frankford Trans. Ctr."),
    ("9", "9 - Andorra to Independence Mall"),
    ("12", "12 - Kingsessing to Society Hill"),
    ("14", "14 - Oxford Valley & Neshaminy Malls to Frankford Trans. Ctr."),
    ("17", "17 - South Philadelphia to Penn&#39;s Landing"),
    ("18", "18 - Cedarbrook to Fox Chase"),
    ("19", "19 - Krewstown to Frankford Trans. Ctr."),
    ("20", "20 - Franklin Mills Mall to Frankford Trans. Ctr."),
    ("21", "21 - 69th Street Trans. Ctr. to Penn&#39;s Landing"),
    ("22", "22 - Warminster to Olney Trans. Ctr."),
    ("23", "23 - Chestnut Hill to South Philadelphia"),
    ("24", "24 - Southampton to Frankford Trans. Ctr."),
    ("25", "25 - Columbus Comm. to Frankford Trans. Ctr."),
    ("26", "26 - Germantown to Frankford Trans. Ctr."),
    ("27", "27 - Plymouth Meeting Mall to Center City"),
    ("28", "28 - Tacony to Fern Rock Trans. Ctr."),
    ("29", "29 - South Philadelphia Crosstown"),
    ("30", "30 - 69th Street Trans. Ctr. to 30th Street Station"),
    ("31", "31 - Overbrook Park to Center City"),
    ("32", "32 - Roxborough to Center City"),
    ("33", "33 - Tioga to Penn&#39;s Landing"),
    ("35", "35 - Manayunk - Roxborough Loop"),
    ("37", "37 - South Philadelphia to Chester Trans. Ctr."),
    ("38", "38 - Ind. Mall to Wissahickon Trans. Ctr."),
    ("39", "39 - Strawberry Mansion to Kensington"),
    ("40", "40 - West Park to Society Hill"),
    ("42", "42 - Wycombe to Penn&#39;s Landing"),
    ("43", "43 - Parkside to Kensington"),
    ("44", "44 - Ardmore/Gladwyne to Independence Mall"),
    ("46", "46 - Overbrook to Angorra"),
    ("47", "47 - Olney to South Philadelphia"),
    ("47m", "47m - South Philadelphia to 7th & Spring Garden"),
    ("48", "48 - North Philadelphia To Penn&#39;s Landing"),
    ("50", "50 - Phila. Park & Parx Casino to Frankford Trans. Ctr."),
    ("52", "52 - Wynnefield/Bala to Kingsessing"),
    ("53", "53 - West Mt Airy to Hunting Park"),
    ("54", "54 - Port Richmond to Strawberry Mansion"),
    ("55", "55 - Doylestown to Olney Trans. Ctr."),
    ("56", "56 - Tacony to Nicetown"),
    ("57", "57 - South Philadelphia to Fern Rock Trans. Ctr."),
    ("58", "58 - Neshaminy Mall to Frankford Trans. Ctr."),
    ("59", "59 - Bells Corner to Arrott Trans. Ctr."),
    ("60", "60 - Port Richmond to East Falls"),
    ("61", "61 - Roxborough to Center City"),
    ("62", "62 - Andorra to Center City"),
    ("64", "64 - Parkside to Pier 70"),
    ("65", "65 - 69th Street Trans. Ctr. to Germantown"),
    ("66", "66 - Morrell Park to Frankford Trans. Ctr."),
    ("67", "67 - Franklin Mills Mall to Frankford Trans. Ctr."),
    ("68", "68 - South Philadelphia to UPS"),
    ("70", "70 - Torresdale to Fern Rock Trans. Ctr."),
    ("71", "71 - The Navy Yard Shuttle"),
    ("73", "73 - Port Richmond to Frankford Trans. Ctr."),
    ("75", "75 - Nicetown to Arrott Trans. Ctr."),
    ("77", "77 - Chestnut Hill to Northeast Philadelphia"),
    ("78", "78 - Cornwells Heights Express"),
    ("79", "79 - South Philadelphia Crosstown"),
    ("80", "80 - Horsham to Olney Trans. Ctr."),
    ("84", "84 - Somerton to Frankford Trans. Ctr."),
    ("88", "88 - Bethayres to Frankford Trans. Ctr."),
    ("89", "89 - Arrott Trans. Ctr. to Kensington"),
    ("90", "90 - Norristown Trans. Ctr. to Plymouth Meeting"),
    ("91", "91 - Norristown Trans. Ctr. to Graterford"),
    ("92", "92 - West Chester to King of Prussia"),
    ("93", "93 - Norristown Trans. Ctr. to Pottstown"),
    ("94", "94 - Chestnut Hill to Montgomery Mall"),
    ("95", "95 - Plymouth Meeting Mall to Swedeland"),
    ("96", "96 - Norristown Trans. Ctr. to Lansdale"),
    ("97", "97 - Norristown Trans. Ctr. to Chestnut Hill"),
    ("98", "98 - Norristown Trans. Ctr. to Willow Grove Mall"),
    ("99", "99 - Norristown Trans. Ctr. to Phoenixville"),
    ("103", "103 - 69th Street Trans. Ctr. to Ardmore"),
    ("104", "104 - 69th Street Trans. Ctr. to West Chester Univ."),
    ("105", "105 - 69th Street Trans. Ctr. to Paoli"),
    ("106", "106 - 69th Street Trans. Ctr. to Ardmore/Paoli"),
    ("107", "107 - 69th Street Trans. Ctr. to Lawrence Park"),
    ("108", "108 - 69th Street Trans. Ctr. to PHL/UPS"),
    ("109", "109 - 69th Street Trans. Ctr. to Chester Trans. Ctr."),
    ("110", "110 - 69th Street Trans. Ctr. to Penn State"),
    ("111", "111 - 69th Street Trans. Ctr. to Chadds Ford"),
    ("112", "112 - 69th Street Trans. Ctr. to Del. Co. Comm. Coll."),
    ("113", "113 - 69th Street Trans. Ctr. to Tri-State Mall"),
    ("114", "114 - Darby Trans. Ctr. to Granite Run Mall"),
    ("115", "115 - Ardmore to Airport Business Center"),
    ("116", "116 - 69th Street Trans. Ctr. to USPS Eastwick"),
    ("117", "117 - Feltonville to Penn State"),
    ("118", "118 - Chester Trans. Ctr. to Newtown Square"),
    ("119", "119 - Harrah&#39;s Chester to Cheyney University"),
    ("120", "120 - 69th Street Trans. Ctr. to Cheyney Univ."),
    ("123", "123 - 69th Street Trans. Ctr. to King of Prussia"),
    ("124", "124 - Center City to Chesterbrook"),
    ("125", "125 - Center City to Valley Forge"),
    ("127", "127 - Neshaminy Mall to Trenton"),
    ("128", "128 - Neshaminy Mall to Oxford Valley Mall"),
    ("129", "129 - Oxford Valley Mall to Morrell Park"),
    ("130", "130 - Franklin Mills to Bucks Cty. Comm. College"),
    ("131", "131 - Norristown Trans. Ctr. to Audubon"),
    ("132", "132 - Montgomery Mall to Telford"),
    ("134", "134 - Chestnut Hill to Montgomery Mall"),
    ("139", "139 - King of Prussia to Phila. Premium Outlets"),
    ("150", "150 - Plymouth Meeting Mall to Parx Casino"),
    ("201", "201 - Ft. Washington Station to Office Center"),
    ("204", "204 - Paoli Station to Eagleview"),
    ("205", "205 - Paoli Station to Phoenixville"),
    ("206", "206 - Paoli Station to Great Valley Corp. Ctr."),
    ("304", "304 - Morrell Park to Bristol"),
    ("306", "306 - West Chester to Great Valley"),
    ("310", "310 - Horsham Breeze"),
    ("314", "314 - West Chester to Goshen Corporate Park"),
    ("C", "C - South Philadelphia to West Oak Lane/Fern Rock"),
    ("G", "G - South Philadelphia to Lankenau Hospital"),
    ("J", "J - Bridesburg to Germantown"),
    ("K", "K - East Falls to Arrott Trans. Ctr."),
    ("L", "L - Plymouth Meeting Mall to Olney Trans. Ctr."),
    ("R", "R - Wissahickon to Frankford Trans. Ctr."),
    ("HXH", "HXH - West Oak Lane to Tioga"),
    ("BSO", "BSO - Fern Rock Trans. Ctr. to South Philadelphia"),
    ("LUCY", "LUCY - Loop through University City"),
    ("MFO", "MFO - 69th Street Trans. Ctr. to Frankford Trans. Ctr.")
  ]

  ALL = TROLLEYS + BUSES
